Added project files
EMus88/go-musthave-shortener-tpl pull request #1
Opened 2021-12-25 18:07 UTC by EMus88

2021-12-27 10:26 UTC, lugingf requested changes
Решение рабочее, в общем все хорошо. Пара небольших вопросов и замечаний, больше по оформлению и нэимингу.

2021-12-27 10:26 UTC, lugingf commented on internal/app/service/service.go
> +type UseStorage interface {
Почему `UseStorage`? По названию будто это не интерфейс, а метод, который возвращает `bool`

2021-12-27 10:26 UTC, lugingf commented on pkg/idgenerator/IDgenerator.go
> +func CreateID() *string {
А зачем мы тут отдаем указатель?

2021-12-27 10:26 UTC, lugingf commented on internal/repository/repository.go
> +	us.mx.Lock()
Кайф что ты про это подумал! Решение хорошее, рабочее. Но есть секрет - на очень большой нагрузке это может не спасти :)

На твое усмотрение: есть для таких целей удобная `sync.Map`

2021-12-27 10:26 UTC, lugingf commented on internal/app/service/service.go
> +type UseStorage interface {
Но идея скрыть реализацию репозитория за интерфейсом - очень хорошая! За это отдельное спасибо!

2021-12-27 10:26 UTC, lugingf commented on internal/handler/handler_post_test.go
> +package handler
Вообще думаю их можно было в одном файле разместить.

2021-12-27 10:26 UTC, lugingf commented on internal/handler/handler.go
> +	fmt.Println(id + " / " + string(body))
это логирование?

2021-12-27 10:26 UTC, lugingf commented on internal/app/service/storageService.go
> +type StorageService struct {
Я прям путаюсь в названиях.
Давай чуть-чуть перетасуем. У нас будет три слоя приложения
Сетевой - это хэндлеры
Уровень БД - это репозиторий/storage
Уровень Service - это доменная логика (в нашем случае это генерация короткого url)

И по идее обработка по такой логике
Хэндлер принимает запрос. Вызывает Сервисную часть, чтобы она отработала свою логику.
Сервисная часть отрабатывает логику, если необходимо - обращается к репозиторию, отдает результат
Хэндлер результат зарорачивает в респонс, если это нужно

2021-12-27 10:27 UTC, lugingf commented
А, еще куда-то тесты пропали. Тут по идее должен запускаться пайплайн с тестами под все инкременты

2021-12-27 19:01 UTC, lugingf approved these changes
Все хорошо. Спасибо за правки.
Написал несколько комментов, но они не принципиальные. Принимаю как есть.

Насчет нейминга - попрошу поправить в следующих инкрементах

2021-12-27 19:01 UTC, lugingf commented on internal/app/service/service.go
> +type Repositiries interface {
Не приоритетно - имена интерфейсов лучше в единственном числе.

Логика такая - Интерфейс репозиторий. Каждая имплементация этого интерфейса - это какой-то "репозиторий" для какой-то доменной сущности.

2021-12-27 19:01 UTC, lugingf commented on internal/app/service/service.go
> +type Repositiries interface {
+ Тут опечатка `RepositOry`

2021-12-27 19:01 UTC, lugingf commented on internal/app/service/service.go
> +	GetURLfromStorage(id string) string
Постфиксы `toStorage` тут лишние :) Лучше методы сервиса переназвать, если тебя смущают одинаковые названия

2021-12-27 19:01 UTC, lugingf commented on internal/handler/handler.go
> +	c.String(http.StatusCreated, "http://localhost:8080/"+id)
Не приоритетно - тут норм. Но прямая конкатенация медленная и ее стараются не применять. Обычно пользуются пакетами `fmt` или `strings`

2021-12-28 16:34 UTC, EMus88 commented
Done increment 3

2021-12-28 16:42 UTC, merged